version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - '5432:5432'

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db